### PR TITLE
Gomod v2

### PR DESCRIPTION
**Pull request by daxmc99**
Upgrade to go modules and moby attempting to minimize changes.

### CODE REVIEW

**Comment by luthermonson** [comment]
@daxmc99 Much less changes with this version without the update command. Let's get some sign off from others and merge this as I'll probably update the libs that still need the proxy in the near future so let's just get this party rolling.

**Comment by ibuildthecloud** [comment]
LGTM can we merge this?

**Comment by dramich** [comment]
`github.com/codegangsta/cli` > `github.com/urfave/cli` before we can merge or anyone on go 1.12 will be broken when attempting to do dependency changes.

**Comment by daxmc99** [comment]
@dramich Fixed

**Comment by dramich** [comment]
LGTM

**Pull request merged**
