### PR TITLE
Support vSphere network protocol profiles

### PR DESCRIPTION
**Pull request by kinolaev**
Part of rancher/rancher#15817

Added params:

- `vmwarevsphere-vapp-ipprotocol`
- `vmwarevsphere-vapp-ipallocationpolicy`
- `vmwarevsphere-vapp-transport`
- `vmwarevsphere-vapp-property`

### CODE REVIEW

**Comment by loganhz** [comment]
@StrongMonkey Can you help to review this PR, please?

**Comment by StrongMonkey** [comment]
LGTM. @kinolaev can you squash your commits into a single one?

**Comment by kinolaev** [comment]
Done.

Thank you @StrongMonkey!

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
