### PR TITLE
[WIP] Accept registry options for create command

### PR DESCRIPTION
**Pull request by ryansann**
Issue:
- rancher/rancher#26366

This adds the ability to authenticate to a private registry during the machine provisioning process, which enables docker run commands that use images from that private registry.

Example:
```bash
MACHINE_REGISTRY_USERNAME=user MACHINE_REGISTRY_PASSWORD=xxxxx 
MACHINE_REGISTRY_URL=registry.example.com rancher-machine --debug create -d digitalocean --engine-install-url 
https://releases.rancher.com/install-docker/19.03.sh --digitalocean-size s-2vcpu-2gb --digitalocean-ssh-port 22
--digitalocean-access-token xxxxx --digitalocean-image ubuntu-18-04-x64 --digitalocean-ssh-user root 
--digitalocean-region sfo2 node-test
```

### CODE REVIEW

**Comment by luthermonson** [comment]
looks like this is only in the `create` command. think we need a `login` or a `registry` command with login/logout so we can control it after create/provision? i had suggested it be a global option but definitely makes sense in `create` but looking at it in `create` makes me wonder if we need to control this more granularly like re-login or anything after the vm is created. For example could catch container pull auth errors on clusters with  private registries and attempt a login again? 

i definitely love this implementation better than what we looked at friday.

**Comment by Oats87** [comment]
@ryansann @luthermonson Is the goal of this functionality to only authenticate against a private registry for the specific `docker run` command for the `rancher/rancher-agent` we run? AFAICT this will only create a corresponding docker config file for whatever the provisioning user is on the host, which may throw certain folks expectations off if they are expecting this to just blindly make the docker daemon authenticate against a registry.

**Comment by ryansann** [comment]
@Oats87  the goal is to allow us to create a machine that's setup to talk to a private registry. From Rancher's side, this would be leveraged in the `docker run` for the agent as you say, with the agent image being pulled from a private registry. There is a docker config file created, which seems pretty unavoidable. If this could cause issues, perhaps a separate login/logout command would be better as @luthermonson suggested.

**Comment by Oats87** [comment]
> @Oats87 the goal is to allow us to create a machine that's setup to talk to a private registry. From Rancher's side, this would be leveraged in the `docker run` for the agent as you say, with the agent image being pulled from a private registry. There is a docker config file created, which seems pretty unavoidable. If this could cause issues, perhaps a separate login/logout command would be better as @luthermonson suggested.

I'm not actually concerned about whether that docker config file is created or not, but if I'm not mistaken, that docker config file is created only for the user that actually executes the `docker login`, i.e. there is not a configuration being pushed into place to universally allow a node to pull from whatever registry in an authenticated manner. I'm not sure why we don't move that `docker login` logic via `ssh` into `rancher/rancher` itself, where it is actually running the `docker run`

**Comment by ryansann** [comment]
Closing this after discussing further w/ @Oats87

**Pull request closed without merging**
