### PR TITLE
Virt box

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud @sheng-liang

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Awesome!!! I'll just need to test.  VirtualBox crashes on my machine (not related to this, just sucks in general).  Once we release v0.3.1 you can submit this PR to upstream.

**Comment by wlan0** [comment]
@ibuildthecloud  debugSSHCommand should not be removed

We had this conversation, about not waiting for Restart as Restart breaks the SSH connection. In case there is an error during restart, it needs to be shown in some way. That is done by debugSSHCommand

The function prints output if --debug flag is set in machine

**Comment by wlan0** [comment]
The reason I call cloud init before starting userdocker is that we set the tlsConfiguration for userdocker via a config file in /var/lib/rancher/conf/cloud-config.d/

this config file has to be merged and used when docker is started again. That is achieved by calling cloud-init

**Comment by ibuildthecloud** [comment]
Okay, thanks, that makes sense

**Pull request closed without merging**
