### PR TITLE
Rancher v0.15.0

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Not mergeable but this is rebased on docker-machine v0.15.0. Need darren to push to a new branch and release.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/11192

**Comment by deniseschannon** [comment]
@StrongMonkey why do we need a new branch?

**Comment by StrongMonkey** [comment]
@ibuildthecloud @deniseschannon this branch can be force pushed to master now.

**Comment by ibuildthecloud** [comment]
Pushed to master

**Pull request merged**
