### PR TITLE
Add new regions and corresponding AMIs

### PR DESCRIPTION
**Pull request by furkatgofurov7**
We have added new regions in https://github.com/rancher/ui/pull/5037 to the rancher UI and the new regions are visible. However when validating them, it was noticed that there is mismatch between, supported AWS region list for Cloud credentials <-> AWS region list for provisioning EKS clusters. More info here: https://github.com/rancher/dashboard/issues/8701#issuecomment-1594433260

This PR adds those new regions to the regions list with it's corresponding AMIs from https://cloud-images.ubuntu.com/locator/ec2/

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@rmweir can PTAL, thanks!

**Comment by rmweir** [comment]
@furkatgofurov7 my bad but these look out of date now. Please update. Anyone can approve these PRs as long as they check the AMIs against the list, this includes UI.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 my bad but these look out of date now. Please update. Anyone can approve these PRs as long as they check the AMIs against the list, this includes UI.

@rmweir updated now

**Review by rmweir — DISMISSED** [review]
LGTM

**Comment by rmweir** [comment]
Looks like a test is failing so LGTM once that is fixed.

**Comment by furkatgofurov7** [comment]
All tests are failing with the same message: `failed to read user data file "/tmp/awsuserdata2230056578/does-not-exist.yml": open /tmp/awsuserdata2230056578/does-not-exist.yml: no such file or directory`

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
The CI fails because the function [TestValidateAwsRegionInvalid](https://github.com/rancher/machine/blob/2c59804f13cd37d2faad2017047c1d40264e0674/drivers/amazonec2/amazonec2_test.go#L129-L137) expects the region "eu-central-2" is not in the `regionDetails` list. 

To make the CI happy, you must change the above function to use another value for testing.

**Comment by furkatgofurov7** [comment]
@rmweir @jiaqiluo can you PTAL and help merging this before it gets outdated again, thanks!

**Review by jiaqiluo — APPROVED** [review]
LGTM as the CI passed.

**Pull request merged**
