### PR TITLE
Fixed issue where openstack keypair were leaked on instance creation error

### PR DESCRIPTION
**Pull request by rodcloutier**
This PR intends to fix an issue where openstack keypair were leaked when an error occurred on instance creation.

### CODE REVIEW

**Comment by daxmc99** [comment]
Is there a rancher/rancher issue for this?

**Comment by rodcloutier** [comment]
@daxmc99 I don't think there is one. We encountered the issue with our fork of the code. We thought that it could benefit the community to have the fix.

**Comment by daxmc99** [comment]
Hi @rodcloutier, 
Could you make an issue with the steps to reproduce the problem? Then I could assign it over to our qa team to test it after merging.

**Comment by cjellick** [comment]
we aren't really investing at all in the openstack driver at this time

**Pull request closed without merging**
