### PR TITLE
Increase interval, add clean up

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
1 second interval is too aggressive if a large number of host is being provisioned at the same. It will hit rate limiting in DigitalOcean api.

**Comment by StrongMonkey** [comment]
Fix https://github.com/rancher/rancher/issues/27010

**Comment by cbron** [comment]
How would this fix the removal of nodes ? Is it that multiple nodes get created by accident at start time so the removal only cleans up ones it knows about ? In the screen cap it doesn't look like that is the case, even though I have seen that happen.

**Comment by StrongMonkey** [comment]
@cbron It addresses two bugs:
1. If GET request fails when fetching the droplets, docker machine will not try to clean up the node. This adds the clean up if get failed. 
2. Increase the interval to 5 seconds. This reduces the number of calls to the API. The problem is that once you hit rate limiting, the DELETE action will also fail.

The bug is that when multiple nodes get created due to the rate limiting, docker-machine will exit and leave the orphan instance.

**Pull request merged**
