### PR TITLE
Updating the github.com/vmware/govmomi driver to 0.19.0

### PR DESCRIPTION
**Pull request by Oats87**
Changing vsphere driver to be compatible with new 0.19.0 API
Resolves https://github.com/rancher/rancher/issues/17207

### CODE REVIEW

**Comment by ernst-at-tv2** [comment]
@Oats87 has the code been tested against a vsphere cluster? we really need this to get merged into master so we can spin up an on-prem cluster 🙂 let me know if I can help in any way!

**Comment by ernst-at-tv2** [comment]
@Oats87 just complied it and it seems to runs just fine :) created a vm and attached the network, nice 🙂

**Comment by JasonvanBrackel** [comment]
@Oats87, can you resolve that conflict and @deniseschannon when that happens can we get this PR'd?

**Comment by Oats87** [comment]
Hi @ernst-at-tv2 and @JasonvanBrackel 

This has in fact been tested against a vSphere cluster, I have been working to try and determine any potential issues we may hit regarding the crazy large version upgrade.

**Comment by ernst-at-tv2** [comment]
@Oats87 I've build a couple of test clusters and played around with them, destroyed them and re-provisioned. So far I've yet to to hit any bugs 👍

**Pull request closed without merging**
